version: "2"
services:
  profile-ms:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - profile-db
    labels:
      io.rancher.scheduler.affinity:host_label: id=n2
  profile-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: profile_db
      MYSQL_PASSWORD: 'my-secret'
      MYSQL_ROOT_PASSWORD: 'my-secret'
      MYSQL_USER: root
    ports:
    - 3307:3306/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: id=n2




