version: "2"
services:
  profile-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: profile
      MYSQL_ROOT_PASSWORD: 'my-secret'
    ports:
    - "3307:3306"
    labels:
      io.rancher.scheduler.affinity:host_label: id=n2
  profile-ms:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - profile-db
    labels:
      io.rancher.scheduler.affinity:host_label: id=n2






